project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    #- "*.Rmd"
    #- "!exercises/exercises.Rmd"
    #- "!slides/[0-9]*.qmd"

website:
  page-navigation: true
  title: "Mastering Data Visualization with R"
  description: "Homepage for Mastering Data Visualization with R"
  site-url: "https://hossainlab.github.io/datavizwithr"
  favicon: "images/logo.png"
  
  repo-url: https://github.com/hossainlab/clinical-reporting-gtsummary-rmed
  repo-actions: [edit, issue]

  open-graph: true
  twitter-card:
    creator: "@hossainlab"
    image: "/images/logo_wall.png"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right: "&copy; Copyright 2024, Md. Jubayer Hossain"
    background: "#708090"

  sidebar:
    background: "#708090"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/chiraltraining/
        text: GitHub
      - icon: facebook
        href: https://www.facebook.com/chiralbd.org
        text: Facebook
      - icon: twitter
        href: https://twitter.com/chiralbd
        text: Twitter
      - icon: linkedin
        href: https://www.linkedin.com/company/chiral-bangladesh/mycompany/?viewAsMember=true
        text: LinkedIn
        
    style: docked
    contents:
     - href: index.qmd
       text: Home
     - href: material.qmd
       text: Material
     - href: setup.qmd
       text: Setup
     - href: q-and-a.qmd
       text: FAQs
     - href: license.qmd
       text: License

format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
    code-copy: true
    code-overflow: scroll
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y

editor: source

